# Generated by Django 4.1.1 on 2022-09-25 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CITY",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, verbose_name="City Name")),
            ],
        ),
        migrations.CreateModel(
            name="ENTITY",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, verbose_name="Entity Name")),
            ],
        ),
        migrations.CreateModel(
            name="ROLE",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, verbose_name="Role Name")),
            ],
        ),
        migrations.CreateModel(
            name="MASTER",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.city"
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.entity"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.role"
                    ),
                ),
            ],
        ),
    ]
